--TB_STATUS_AULA
INSERT INTO TB_STATUS_AULA(STA_STATUS) VALUES ('PENDENTE'),('CONCLUIDA'),('CANCELADA');

--TB_STATUS_ATIVIDADE
INSERT INTO TB_STATUS_ATIVIDADE(STV_STATUS) VALUES ('PENDENTE'),('ENTREGUE'),('ENTREGUE - ATRASADA'),('NÃO ENTREGUE'),('CANCELADA'),('CORRIGIDA');

--TB_NIVEIS_APRENDIZADO
INSERT INTO TB_NIVEIS_APRENDIZADO(NVA_NIVEL_APRENDIZADO) VALUES ('INICIANTE'),('BÁSICO'),('INTERMEDIÁRIO'),('AVANÇADO');

--TB_MATERIAS
INSERT INTO TB_MATERIAS(MAT_NOME) VALUES
('MATEMÁTICA'),
('PORTUGUÊS'),
('LITERATURA'),
('REDAÇÃO'),
('GRAMÁTICA'),
('HISTÓRIA'),
('GEOGRAFIA'),
('CIÊNCIAS'),
('FÍSICA'),
('QUÍMICA'),
('BIOLOGIA'),
('FILOSOFIA'),
('SOCIOLOGIA'),
('INGLÊS'),
('ESPANHOL'),
('ARTES'),
('EDUCAÇÃO FÍSICA'),
('TECNOLOGIA'),
('LINGUAGENS DE PROGRAMAÇÃO'),
('CONHECIMENTOS GERAIS'),
('REFORÇO'),
('CONCURSOS'),
('VESTIBULAR'),
('TEORIA MUSICAL'),
('MÚSICA');

--TB_TIPOS_PERGUNTAS
INSERT INTO TB_TIPOS_PERGUNTA(TPP_TIPO) VALUES ('MÚLTIPLA ESCOLHA'),('VERDADEIRO OU FALSO'),('DISSERTATIVA');