CREATE OR ALTER PROCEDURE PR_I_USUARIO
	@NOME VARCHAR(MAX),
	@EMAIL VARCHAR(MAX),
	@SENHA VARCHAR (MAX),
	@DT_CADASTRO DATETIME2
AS
BEGIN
	INSERT INTO TB_USUARIOS
		(USU_NOME,USU_EMAIL,USU_SENHA,USU_DT_CADASTRO,USU_STATUS)
	VALUES 
		(@NOME, @EMAIL, @SENHA, @DT_CADASTRO, 1);
END
GO

CREATE OR ALTER PROCEDURE PR_I_ALUNO
	@NOME VARCHAR(MAX),
	@EMAIL VARCHAR(MAX),
	@SENHA VARCHAR (MAX),
	@DT_CADASTRO DATETIME2,
	@DT_NASCIMENTO DATETIME2,
	@TELEFONE VARCHAR(MAX) = NULL,
	@OBSERVACAO VARCHAR(MAX) = NULL,
	@ID_NIVEL_APRENDIZADO INT
AS
BEGIN
	DECLARE @ID_OUTPUT INT = 0;

	BEGIN TRY
		BEGIN TRANSACTION;

		INSERT INTO TB_USUARIOS
			(USU_NOME,USU_EMAIL,USU_SENHA,USU_DT_CADASTRO,USU_STATUS)
		VALUES 
			(@NOME, @EMAIL, @SENHA, @DT_CADASTRO, 1);

		SET @ID_OUTPUT = SCOPE_IDENTITY();

		INSERT INTO TB_ALUNOS 
			(ALU_DT_NASCIMENTO, ALU_OBSERVACAO, ALU_TELEFONE, ALU_USU_ID, ALU_NVA_ID)
		VALUES
			(@DT_NASCIMENTO, @OBSERVACAO, @TELEFONE, @ID_OUTPUT, @ID_NIVEL_APRENDIZADO);
		
		COMMIT;
	END TRY

	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK;
		THROW;
	END CATCH;
END