CREATE OR ALTER PROCEDURE PR_I_USUARIO
	@NOME VARCHAR(MAX),
	@EMAIL VARCHAR(MAX),
	@SENHA VARCHAR (MAX),
	@DT_CADASTRO DATETIME2
AS
BEGIN
	INSERT INTO TB_USUARIOS
		(USU_NOME,USU_EMAIL,USU_SENHA,USU_DT_CADASTRO,USU_STATUS)
	VALUES 
		(@NOME, @EMAIL, @SENHA, @DT_CADASTRO, 1);
END