CREATE DATABASE ENSILY;

USE ENSILY;

CREATE TABLE TB_USUARIOS(
	USU_ID INT IDENTITY NOT NULL,
	USU_NOME VARCHAR(500) NOT NULL,
	USU_EMAIL VARCHAR(500) NOT NULL,
	USU_SENHA VARCHAR(500) NOT NULL,
	USU_DT_CADASTRO DATETIME2 NOT NULL,
	USU_STATUS BIT NOT NULL,
	CONSTRAINT PK_USU PRIMARY KEY (USU_ID)
);

CREATE TABLE TB_NIVEIS_APRENDIZADO(
	NVA_ID INT IDENTITY NOT NULL,
	NVA_NIVEL_APRENDIZADO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_NVA PRIMARY KEY (NVA_ID)
);

CREATE TABLE TB_ALUNOS(
	ALU_ID INT IDENTITY NOT NULL,
	ALU_DT_NASCIMENTO DATETIME2 NOT NULL,
	ALU_OBSERVACAO VARCHAR(1000),
	ALU_USU_ID INT NOT NULL,
	ALU_NVA_ID INT NOT NULL,
	CONSTRAINT PK_ALU PRIMARY KEY (ALU_ID),
	CONSTRAINT FK_ALU_USU FOREIGN KEY (ALU_USU_ID) REFERENCES TB_USUARIOS (USU_ID),
	CONSTRAINT FK_ALU_NVA FOREIGN KEY (ALU_NVA_ID) REFERENCES TB_NIVEIS_APRENDIZADO (NVA_ID)
);

CREATE TABLE TB_PROFESSORES(
	PRF_ID INT IDENTITY NOT NULL,
	PRF_DESCRICAO VARCHAR(1000) NOT NULL,
	PRF_USU_ID INT NOT NULL,
	CONSTRAINT PK_PRF PRIMARY KEY (PRF_ID),
	CONSTRAINT FK_PRF_USU_ID FOREIGN KEY (PRF_USU_ID) REFERENCES TB_USUARIOS (USU_ID)
);

CREATE TABLE TB_PROFESSORES_ALUNOS(
	PFAL_PRF_ID INT NOT NULL,
	PFAL_ALU_ID INT NOT NULL,
	CONSTRAINT PK_PFAL PRIMARY KEY (PFAL_PRF_ID, PFAL_ALU_ID),
	CONSTRAINT FK_PFAL_PRF FOREIGN KEY(PFAL_PRF_ID) REFERENCES TB_PROFESSORES (PRF_ID),
	CONSTRAINT FK_PFAL_ALU FOREIGN KEY(PFAL_ALU_ID) REFERENCES TB_ALUNOS (ALU_ID)
);

CREATE TABLE TB_MATERIAS(
	MAT_ID INT IDENTITY NOT NULL,
	MAT_NOME VARCHAR (500) NOT NULL,
	CONSTRAINT PK_MAT PRIMARY KEY (MAT_ID)
);

CREATE TABLE TB_MATERIAS_PROFESSORES(
	MTPF_MAT_ID INT NOT NULL,
	MTPF_PRF_ID INT NOT NULL,
	CONSTRAINT PK_MTPF PRIMARY KEY (MTPF_MAT_ID, MTPF_PRF_ID),
	CONSTRAINT FK_MTPF_MAT FOREIGN KEY(MTPF_MAT_ID) REFERENCES TB_MATERIAS (MAT_ID),
	CONSTRAINT FK_MTPF_PRF FOREIGN KEY(MTPF_PRF_ID) REFERENCES TB_PROFESSORES (PRF_ID)
);

CREATE TABLE TB_MATERIAIS(
	MTR_ID INT IDENTITY NOT NULL,
	MTR_TITULO VARCHAR (500) NOT NULL,
	MTR_DESCRICAO VARCHAR (1000),
	MTR_URL VARCHAR (2000)
	CONSTRAINT PK_MTR PRIMARY KEY (MTR_ID)
);

CREATE TABLE TB_MATERIAS_MATERIAIS(
	MTMA_MAT_ID INT NOT NULL,
	MTMA_MTR_ID INT NOT NULL,
	CONSTRAINT PK_MTMA PRIMARY KEY (MTMA_MAT_ID, MTMA_MTR_ID),
	CONSTRAINT FK_MTMA_MAT FOREIGN KEY(MTMA_MAT_ID) REFERENCES TB_MATERIAS (MAT_ID),
	CONSTRAINT FK_MTMA_MTR FOREIGN KEY(MTMA_MTR_ID) REFERENCES TB_MATERIAIS (MTR_ID)
);

CREATE TABLE TB_STATUS_AULA(
	STA_ID INT IDENTITY NOT NULL,
	STA_STATUS VARCHAR(100) NOT NULL,
	CONSTRAINT PK_STA PRIMARY KEY (STA_ID)
);

CREATE TABLE TB_AULAS(
	AUL_ID INT IDENTITY NOT NULL,
	AUL_DT_HR_INICIO DATETIME NOT NULL,
	AUL_DT_HR_FIM DATETIME NOT NULL,
	AUL_OBSERVACAO VARCHAR(1000),
	AUL_ALU_ID INT NOT NULL,
	AUL_PRF_ID INT NOT NULL,
	AUL_STA_ID INT NOT NULL,
	CONSTRAINT PK_AUL PRIMARY KEY (AUL_ID),
	CONSTRAINT FK_AUL_ALU FOREIGN KEY (AUL_ALU_ID) REFERENCES TB_ALUNOS (ALU_ID),
	CONSTRAINT FK_ALU_PRF FOREIGN KEY (AUL_PRF_ID) REFERENCES TB_PROFESSORES (PRF_ID),
	CONSTRAINT FK_ALU_STA FOREIGN KEY (AUL_STA_ID) REFERENCES TB_STATUS_AULA (STA_ID)
);

CREATE TABLE TB_AULAS_MATERIAIS(
	ALMT_AUL_ID INT NOT NULL,
	ALMT_MTR_ID INT NOT NULL,
	CONSTRAINT PK_ALMT PRIMARY KEY (ALMT_AUL_ID, ALMT_MTR_ID),
	CONSTRAINT FK_ALMT_AUL FOREIGN KEY(ALMT_AUL_ID) REFERENCES TB_AULAS (AUL_ID),
	CONSTRAINT FK_ALMT_MTR FOREIGN KEY(ALMT_MTR_ID) REFERENCES TB_MATERIAIS (MTR_ID)
);

CREATE TABLE TB_HISTORICOS_AULA(
	HCA_ID INT IDENTITY NOT NULL,
	HCA_DT_HR DATETIME NOT NULL,
	HCA_OBSERVARCAO VARCHAR (1000),
	HCA_AUL_ID INT NOT NULL,
	CONSTRAINT PK_HCA PRIMARY KEY (HCA_ID),
	CONSTRAINT FK_HCA_AUL FOREIGN KEY (HCA_AUL_ID) REFERENCES TB_AULAS (AUL_ID)
);

CREATE TABLE TB_TIPOS_PERGUNTA(
	TPP_ID INT IDENTITY NOT NULL,
	TPP_TIPO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_TPP PRIMARY KEY (TPP_ID)
);

CREATE TABLE TB_PERGUNTAS(
	PGT_ID INT IDENTITY NOT NULL,
	PGT_PERGUNTA VARCHAR(1000) NOT NULL,
	PGT_OBRIGATORIA BIT NOT NULL,
	PGT_TPP_ID INT NOT NULL,
	CONSTRAINT PK_PGT PRIMARY KEY (PGT_ID),
	CONSTRAINT FK_PGT_TPP FOREIGN KEY (PGT_TPP_ID) REFERENCES TB_TIPOS_PERGUNTA (TPP_ID)
);

CREATE TABLE TB_STATUS_ATIVIDADE(
	STV_ID INT IDENTITY NOT NULL,
	STV_STATUS VARCHAR(100) NOT NULL,
	CONSTRAINT PK_STV PRIMARY KEY (STV_ID)
);

CREATE TABLE TB_ATIVIDADES(
	ATV_ID INT IDENTITY NOT NULL,
	ATV_TITULO VARCHAR(300) NOT NULL,
	ATV_DESCRICAO VARCHAR(2000) NOT NULL,
	ATV_DT_LIMITE DATETIME NOT NULL,
	ATV_ACEITA_ATRASO BIT NOT NULL,
	ATV_AUL_ID INT,
	ATV_STV_ID INT NOT NULL,
	CONSTRAINT PK_ATV PRIMARY KEY (ATV_ID),
	CONSTRAINT FK_ATV_AUL FOREIGN KEY (ATV_AUL_ID) REFERENCES TB_AULAS(AUL_ID),
	CONSTRAINT FK_ATV_STV FOREIGN KEY (ATV_STV_ID) REFERENCES TB_STATUS_ATIVIDADE(STV_ID)
);

CREATE TABLE TB_ATIVIDADES_PERGUNTAS(
	ATPG_ATV_ID INT NOT NULL,
	ATPG_PGT_ID INT NOT NULL,
	CONSTRAINT PK_ATPG PRIMARY KEY (ATPG_ATV_ID, ATPG_PGT_ID),
	CONSTRAINT FK_ATPG_ATV FOREIGN KEY(ATPG_ATV_ID) REFERENCES TB_ATIVIDADES (ATV_ID),
	CONSTRAINT FK_ATPG_PGT FOREIGN KEY(ATPG_PGT_ID) REFERENCES TB_PERGUNTAS (PGT_ID)
);

CREATE TABLE TB_ENTREGAS_ATIVIDADE(
	EAT_ID INT NOT NULL,
	EAT_DT_ENTREGA DATETIME NOT NULL,
	EAT_OBSERVACAO_ALUNO VARCHAR(1000),
	EAT_ATV_ID INT NOT NULL,
	EAT_ALU_ID INT NOT NULL,
	CONSTRAINT PK_EAT PRIMARY KEY (EAT_ID),
	CONSTRAINT FK_EAT_ATV FOREIGN KEY (EAT_ATV_ID) REFERENCES TB_ATIVIDADES(ATV_ID),
	CONSTRAINT FK_EAT_ALU FOREIGN KEY (EAT_ALU_ID) REFERENCES TB_ALUNOS(ALU_ID)
);

CREATE TABLE TB_CORRECOES(
	CRR_ID INT NOT NULL,
	CRR_NOTA DECIMAL(10,2) NOT NULL,
	CRR_OBSERVACAO VARCHAR(2000),
	CRR_DATA_CORRECAO DATETIME NOT NULL,
	CRR_EAT_ID INT NOT NULL,
	CRR_PRF_ID INT NOT NULL,
	CONSTRAINT PK_CRR PRIMARY KEY(CRR_ID),
	CONSTRAINT FK_CRR_EAT FOREIGN KEY (CRR_EAT_ID) REFERENCES TB_ENTREGAS_ATIVIDADE (EAT_ID),
	CONSTRAINT FK_CRR_PRF FOREIGN KEY (CRR_PRF_ID) REFERENCES TB_PROFESSORES (PRF_ID)
);